// Embeds migrations/*.sql into src/migrations.generated.ts so the Electron bundle needs no file access.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const dir = fileURLToPath(new URL('../migrations/', import.meta.url));
const out = fileURLToPath(new URL('../src/migrations.generated.ts', import.meta.url));
const files = readdirSync(dir).filter((f) => /^\d{4}_[a-z0-9_]+\.sql$/.test(f)).sort();
const entries = files.map((f) => {
  const version = Number(f.slice(0, 4));
  const name = f.slice(5, -4);
  const sql = readFileSync(dir + f, 'utf8');
  return `  { version: ${version}, name: ${JSON.stringify(name)}, sql: ${JSON.stringify(sql)} },`;
});
mkdirSync(fileURLToPath(new URL('../src/', import.meta.url)), { recursive: true });
writeFileSync(out, `// GENERATED by scripts/embed-migrations.ts — do not edit.\nexport interface Migration { version: number; name: string; sql: string }\nexport const MIGRATIONS: readonly Migration[] = [\n${entries.join('\n')}\n];\n`);
console.log(`embedded ${files.length} migrations`);
