/**
 * Generates apps/desktop/src/preload/generated.ts from the IPC contract registry (LLD §10.1).
 * The renderer can only reach declared methods; nothing else crosses the bridge.
 * Run: pnpm --filter @muneem/desktop gen  (imports the built @muneem/contracts dist).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
// Built dist, resolved relative to the repo root (the root package has no dependency on @muneem/contracts).
import { channels } from '../packages/contracts/dist/index.js';

export const PUSH_EVENTS = ['sync.status', 'connectivity.changed', 'session.changed', 'sync.hydration', 'update.status', 'notification.new'] as const;

const groups = new Map<string, string[]>();
for (const ch of [...channels].sort()) {
  const [ns, method] = ch.split('.') as [string, string];
  if (!groups.has(ns)) groups.set(ns, []);
  groups.get(ns)!.push(method);
}

const lines: string[] = [];
lines.push('// GENERATED by scripts/gen-preload.ts from @muneem/contracts — do not edit.');
lines.push("import { contextBridge, ipcRenderer } from 'electron';");
lines.push('');
lines.push('type Envelope = { ok: true; data: unknown } | { ok: false; error: unknown };');
lines.push('const call = (channel: string) => (input: unknown) =>');
lines.push('  ipcRenderer.invoke(channel, input).then((r: Envelope) => (r && r.ok ? r.data : Promise.reject(r ? r.error : { code: "INTERNAL", class: "permanent", message: "empty response" })));');
lines.push('');
lines.push(`export const EXPOSED_CHANNELS = ${JSON.stringify([...channels].sort())} as const;`);
lines.push(`export const EXPOSED_EVENTS = ${JSON.stringify(PUSH_EVENTS)} as const;`);
lines.push('');
lines.push('const api = {');
for (const [ns, methods] of groups) {
  lines.push(`  ${ns}: {`);
  for (const m of methods) lines.push(`    ${m}: call('${ns}.${m}'),`);
  lines.push('  },');
}
lines.push('  events: {');
lines.push('    on(channel: string, cb: (payload: unknown) => void): () => void {');
lines.push('      if (!(EXPOSED_EVENTS as readonly string[]).includes(channel)) throw new Error(`unknown event: ${channel}`);');
lines.push('      const listener = (_e: unknown, payload: unknown) => cb(payload); // the raw IpcRendererEvent never reaches the page');
lines.push('      ipcRenderer.on(channel, listener);');
lines.push('      return () => { ipcRenderer.removeListener(channel, listener); };');
lines.push('    },');
lines.push('  },');
lines.push('};');
lines.push('');
lines.push('export type ExposedApi = typeof api;');
lines.push("contextBridge.exposeInMainWorld('muneem', api);");
lines.push('');

const out = fileURLToPath(new URL('../apps/desktop/src/preload/generated.ts', import.meta.url));
mkdirSync(fileURLToPath(new URL('../apps/desktop/src/preload/', import.meta.url)), { recursive: true });
writeFileSync(out, lines.join('\n'));
console.log(`gen-preload: ${channels.length} methods in ${groups.size} namespaces → ${out}`);
